(function() {var implementors = {};
implementors["cv"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cv/struct.Mat.html\" title=\"struct cv::Mat\">Mat</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cv/videoio/struct.VideoCapture.html\" title=\"struct cv::videoio::VideoCapture\">VideoCapture</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cv/videoio/struct.VideoWriter.html\" title=\"struct cv::videoio::VideoWriter\">VideoWriter</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cv/video/tracking/struct.TermCriteria.html\" title=\"struct cv::video::tracking::TermCriteria\">TermCriteria</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cv/objdetect/struct.CascadeClassifier.html\" title=\"struct cv::objdetect::CascadeClassifier\">CascadeClassifier</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cv/objdetect/struct.SvmDetector.html\" title=\"struct cv::objdetect::SvmDetector\">SvmDetector</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cv/objdetect/struct.HogDescriptor.html\" title=\"struct cv::objdetect::HogDescriptor\">HogDescriptor</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cv/features2d/struct.MSER.html\" title=\"struct cv::features2d::MSER\">MSER</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cv/cuda/struct.GpuMat.html\" title=\"struct cv::cuda::GpuMat\">GpuMat</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cv/cuda/struct.GpuHog.html\" title=\"struct cv::cuda::GpuHog\">GpuHog</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cv/cuda/struct.GpuCascade.html\" title=\"struct cv::cuda::GpuCascade\">GpuCascade</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
